name: barry
services:
  app:
    build:
      context: .
      dockerfile: ./apps/barry/Dockerfile
    depends_on:
      - postgres
    environment:
      - SERVER_HOST=0.0.0.0
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    restart: always

  postgres:
    env_file:
      - .env
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
