name: barry
services:
  app:
    build:
      context: .
      dockerfile: ./apps/barry/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql://barry:password@postgres:5432/barry
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  postgres:
    environment:
      - POSTGRES_DB=barry
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=barry
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
